### PR TITLE
Created Game folder for various games and in that created Hangman folder for Hangman and added readme in it ! changed the Main Readme littlebit !

### PR DESCRIPTION
**Pull request by sudhanshutiwari264**
Reversed string using Python!

### CODE REVIEW

**Comment by auralshin** [comment]
I appreciate your PR , but this repo is for algorithm reversing a string isn't much I'm closing this PR feel free to add something more to it.

**Comment by sudhanshutiwari264** [comment]
Thanks, I will try to add other algorithms also!

**Comment by sudhanshutiwari264** [comment]
But i saw Stone paper scissors game in python algo ! does the game algorithm is allowed!

**Comment by sudhanshutiwari264** [comment]
Please check the Main Readme before merging it because it may have some bug !

**Comment by sudhanshutiwari264** [comment]
@auralshin Can you please add hactoberfest accepted label to this for accepted pr

**Pull request merged**
